List vesselTypes = ['Fishing', 'Yacht', 'Leisure Cruise', 'Party Boat'];
List yachtTypes = ['Motor', 'Sail'];
List fishingVesselTypes = ['Air', 'Bass', 'Bay Boat', 'Catamaran', 'Center Console', 'Convertible', 'Cuddy Cabin', 'Flats Boat - Skiff', 'Flybridge Sportfishing', 'Inflatable', 'Pilothouse', 'Pontoon'];
List fishingTypes = ['Backcountry', 'Flats', 'Inshore', 'Lake', 'Nearshore', 'Offshore', 'Reed', 'River', 'Wreck'];
List bookingTimes = ['Hourly', 'Daily', 'Weekly', 'Monthly'];
List vesselDurations = ['1', '2', '3', '4', '5', '6', '7', '8'];
List features = [
  'Air Conditioning',
  'At Anchor Stabilizer',
  'BBQ',
  'Beach Club',
  'Beauty Room',
  'Conference',
  'Disabled Accessible',
  'Diving Equipment',
  'Elevator',
  'Fans',
  'Fishing Equipment',
  'Floats',
  'Full Kitchen',
  'Gym',
  'Inflatable Island',
  'Jacuzzi',
  'Jet Ski',
  'Jetpack',
  'Kayak',
  'Linens',
  'Movie Theatre',
  'Paddle Board',
  'Scooter',
  'Snorkel Gear',
  'Sound System',
  'Spa',
  'Stabilizers',
  'Steam Room',
  'Suana',
  'Swimming Pool',
  'Tender',
  'Underwater Camera',
  'Wakeboard',
  'Water Ski',
];
List yachtBuilders = [
  'Any',
  'A.F. Theriault & Sons Shipyard',
  'ABD Aluminum Yachts',
  'Abeking and Rasmussen',
  'Acico Yachts',
  'Ada Yacht Works',
  'Admiral',
  'Allan Ellis Custom',
  'Allan Tongs',
  'Alloy',
  'AllSeas',
  'Aluship',
  'Amels previously Amels-Holland',
  'American Custom Yachts',
  'American Skier',
  'Andrée & Rosenqvist',
  'Aprea Mare',
  'Aquanaut Yachting',
  'Arcadia Yachts',
  'Arkin Pruva',
  'ARS Monaco',
  'Asetilleros Sermiento',
  'Astilleros M. Cies',
  'Atlantic Yachts',
  'Auroux',
  'Aylward Trawlers',
  'Azimut Yachts',
  'Baia Italy',
  'Barbo Yachting',
  'Bartlett Marine Ltd',
  'Bayliner',
  'Beneteau',
  'Beneteau',
  'Benetti',
  'Blohm + Voss',
  'Bluewater Yachts',
  'Boston Whaler',
  'Broward Marine formerly Broward Yachts',
  'Bruckmann Yachts',
  'Brunswick Boat Group',
  'BSC Marine Group',
  'Bucklers Hard Boat Builders (Nelson Cruisers)',
  'Burger Boats',
  'Cabo Yachts sportfishing boats',
  'Cantieri di Pisa',
  'Carter Marine',
  'Carver Yachts a Genmar company',
  'Centurion Boats',
  'Chaparral Boats',
  'Cheoy Lee Shipyard',
  'Chris-Craft Boats',
  'Cimmarron Boats',
  'Clyde Boats',
  'Cobalt Boats',
  'Codecasa',
  'Conquest Yachts',
  'Correct Craft',
  'Corsair Marine',
  'Covey Island Yachts',
  'Crescent Custom Yachts',
  'Crosswater',
  'Cruisers Yachts',
  'CW Hood Yachts',
  'Dalla Pieta',
  'De Birs Yachts',
  'DellaPasquadc',
  'Delta Yachts',
  'Dettling Yacht Company',
  'Dovercraft Yachts',
  'Egg Harbor',
  'Evinrude',
  'Fairline Yachts',
  'Farrier Marine',
  'Feadship Holland (Netherlands)',
  'Ferretti Yachts',
  'Front Street Shipyard',
  'Genesis Yachts',
  'Glastron',
  'Gozzard Ontario Canada',
  'Grand Banks Trawler Yachts and Eastbay Cruisers',
  'Grand Harbour Yachts',
  'Gulf Craft',
  'Guy Couach',
  'Hakvoort Yachts',
  'Hanse Yachts',
  'Hardy Marine',
  'Hatteras Yachts',
  'Herbert Woods',
  'Hinkley Yachts',
  'Horizon Yachts',
  'Huckins Yacht',
  'ICON Yachts',
  'Island Packet Yachts',
  'Island Pilot',
  'J/Boats',
  'Jade Yachts',
  'Jeanneau',
  'Jefferson Yachts',
  'Kadey-Krogen Yachts',
  'KaiserWerft',
  'Kha Shing',
  'Knight & Carver Yachts',
  'Ladenstein Yacht',
  'Lazzara Yachts',
  'LeClercq Marine Yachts',
  'Lightwave Yachts',
  'Lissen Yachts',
  'Lowe Boats',
  'Luhrs Yachts',
  'Lürssen Yachts',
  'Lyman-Morse Boatbuilding',
  'M2 MotorYachts',
  'Macquarie International Motor Yachts',
  'Magnum Marine',
  'Maiora Yachts',
  'Malibu Boats',
  'Marchi',
  'Mariner Yachts International',
  'Marlow Explorer Yachts',
  'Marquis Yachts was a Genmar company',
  'MasterCraft',
  'Maxum',
  'McKinna',
  'Mikelson Yachts',
  'Millennium Super Yachts',
  'Monachus Yachts',
  'Mondomarine',
  'Morgan Yachts',
  'Mulder Shipyard',
  'Nautique',
  'Nautor\'s Swan',
  'Navigator Yachts',
  'Neils Helleberg Yacht Design Alden Yachts',
  'Neptunus Yachts',
  'Neville Trawlers',
  'New Ocean Yachts',
  'Newport Runabout',
  'No Limit Ships',
  'Nobiskrug',
  'Nord West',
  'Nordhavn Yachts and Trawlers',
  'Northern Marine',
  'Ocean Alexander',
  'Ocean Alexander Motor Yachts',
  'OceanAire Yachts',
  'Oceanfast Yachts',
  'Oportal',
  'Ozkalay Yachts by Agantur Inc.',
  'Pacific Mariner',
  'Pacific Motor Yachts',
  'Palmer Johnson Yachts',
  'Pearson Yachts',
  'Perini Navi',
  'Peter Nichols',
  'Piney Creek Boat Builders Suwanee',
  'Pogo Structures',
  'Porta-bote',
  'Post Yachts',
  'Princess',
  'Princess Yachts',
  'Queenship Yachts',
  'Revenge Yachts',
  'Riva Yachts',
  'Riviera',
  'Rodriguez',
  'Royal Yacht',
  'Sabre Yachts',
  'San Juan Yachts',
  'Sea Force IX',
  'Sea Gem Custom Yachts',
  'Sea Ray',
  'Seahorse Marine',
  'Sealine',
  'Sealord England',
  'Seaton Yachts',
  'Shannon Yachts',
  'Sharaf Yachts UAE',
  'Shelter Island Runabout by CH Marine',
  'Silverton Marine',
  'Ski Nautique',
  'Skipper Liner',
  'Spencer Yachts',
  'StanCraft Boat Company',
  'Starcraft Marine',
  'Storebro',
  'Su Marine Yachts',
  'Sunnfjord',
  'Sunreef Yachts',
  'Sunseeker Yachts',
  'Symbol Yacht',
  'Ta shing',
  'Tarrab Yachts',
  'Tecnomar',
  'Tiara',
  'Tiara Yachts',
  'Tiffany Yachts',
  'Timmerman Yachts',
  'Titan Custom Yachts',
  'Tollycraft',
  'TOMCO American Tug',
  'Tradition Trawlers',
  'Trinity Yachts',
  'Trojan Yachts',
  'Tuna Yachts',
  'Uniflite',
  'Vaudrey Miller Tenders',
  'Viking Marin',
  'Viking Sport Cruisers',
  'Viking Yachts',
  'Wacanda Marine',
  'Wadia Boat',
  'Wally Yachts',
  'Waterline Yachts',
  'Wesmac Yachts',
  'West Bay SonShip Yachts Ltd.',
  'Westport Yachts',
  'Wilbur Custom Yachts',
  'Winning Yachts',
  'Yamaha Motor Corporation',
  'Zeta Yachts BC',
];

List licenseTypes = [
  'Six-pack or Charter Boat License',
  '25 Ton Master License',
  '50 Ton Master License',
  '100 Ton Master License',
];
List certificateTypes = [
  'Certificate of Registry',
  'International Tonnage Certificate',
  'International Load-line Certificate',
  'International Load-line Exemption Certificate',
  'Minimum Safe Manning Certificate',
  'International Oil Pollution Prevention Certificate (IOPP)',
  'Document of Compliance (DOC)',
  'Safety Management Certificate',
  'International Sewage Pollution Prevention Certificate',
  'International Ship Security Certificate',
  'Ship Sanitation Control Exemption Certificate',
  'Ship Sanitation Control Certificate',
  'Passenger Ship Safety Certificate',
  'Safety Construction Certificate',
  'Safety Equipment Certificate (Form E)',
  'Safety Radio Certificate (Form R)',
  'Safety Certificate (Form C)',
  'Civil Liability Certificate with respect for damage by Oil Pollution',
  'International Pollution Prevention Certificate for Noxious Liquid substances in Bulk',
  'International Certificate of Fitness for Carriage of Liquefied Gases in Bulk',
  'International Certificate for Carriage of Dangerous Chemicals in Bulk (COF)',
];

List cancellationPolicies = ['Flexible', 'Moderate', 'Strict'];
